spring:
  application:
    name: backend
  
  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/oboe?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${mysql_id}
    password: ${mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}
      password: ${redis_password}
      username: ${redis_username}
  
  # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao_client_id}
            client-secret: ${kakao_client_secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
              - profile_image
              - name
              - gender
              - birthday
              - birthyear
              - phone_number
          naver:
            client-id: ${naver_client_id}
            client-secret: ${naver_client_secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - nickname
              - profile_image
              - gender
              - birthday
              - birthyear
              - mobile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


# 로깅 설정
logging:
  level:
    com.oboe.backend: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true


coolsms:
  apikey: ${sms_key}
  apisecret: ${sms_secret}
  fromnumber: ${sms_number}
